ZQS-1336: Inverse of Block Encoding
zapatacomputing/benchq pull request #109
Opened 2023-07-25 17:03 UTC by olgOk

## Description

- Implementation of the QSP in qiskit (qsp.py).

-  Added the estimation of the parameters for quantum DE solver: number of grid points, matrix condition number, degree of approximating polynomial.

-  Construction of the inverse of block encoding (SEL_inv) using the QSP circuit construction.

## Please verify that you have completed the following steps

- [ ] I have self-reviewed my code.
- [ ] I have included test cases validating introduced feature/fix.
- [ ] I have updated documentation.

2023-07-25 21:09 UTC, AthenaCaesura approved these changes
Just a few minor comments. 🙂

2023-07-25 22:29 UTC, olgOk commented on src/benchq/algorithms/lde_solver.py
> +    grid_qubits = int((np.ceil(np.log2(k)))) + 1
np.ceil returns 'float' datatype but I the number of qubits to be 'int' type.

2023-07-25 22:30 UTC, olgOk commented on src/benchq/algorithms/qsp.py
> +    Lin Lin         linlin (at) math (dot) berkeley (dot) edu
I took this as it was in the original repo, but I will do something about it if needed.

2023-07-26 03:59 UTC, olgOk commented on src/benchq/algorithms/lde_solver.py
> +    by Remez algorithm.
it appears to be in French... I will include Wikipedia's page

2023-07-26 16:10 UTC, AthenaCaesura requested changes

2023-07-26 16:10 UTC, AthenaCaesura commented on src/benchq/algorithms/lde_solver.py
> +    grid_qubits = int((np.ceil(np.log2(k)))) + 1
Then you can just use the builtin `ceil` function.

2023-07-29 04:08 UTC, AthenaCaesura commented on src/benchq/algorithms/qsp.py
> +    Lin Lin         linlin (at) math (dot) berkeley (dot) edu
Nah, the authors probably did that to prevent bots from getting thier emails I guess. No need.

2023-07-29 04:11 UTC, AthenaCaesura approved these changes

2023-08-02 21:57 UTC, merged

2023-08-02 22:26 UTC, max-radin reviewed
Looks great! I left a couple minor comments about the docstrings. Also, ideally we would have a unit test to check that `inverse_blockencoding` works correctly. Is there some choice of `be_matrix`, `matrix_norm`, etc. for which it's straightforward to know what the resulting circuit should be? Or know some property of the circuit?

2023-08-02 22:26 UTC, max-radin commented on src/benchq/algorithms/lde_solver.py
> +            sel_inverse (Circuit): an instance of oqquestra quantum circuit
```suggestion
            sel_inverse (Circuit): an Orquestra quantum circuit
```

2023-08-03 02:55 UTC, olgOk commented on src/benchq/algorithms/lde_solver.py
> +    For the matrix inversion problem, the function to be approximated is 1/x.
Yes, it is only for `1/x`. The formula would be different if approximating other function.

2023-08-03 14:06 UTC, olgOk commented on src/benchq/algorithms/lde_solver.py
> +    For the matrix inversion problem, the function to be approximated is 1/x.
I will adjust this docstring with the next PR. Thank you for pointing this out