Feat: Include utility-scale estimates in the examples
zapatacomputing/benchq pull request #136
Opened 2023-10-09 09:46 UTC by SebastianMorawiec

## Description

Include description of feature this PR introduces or a bug that it fixes. Include the following information:

Added new example that includes utility scale problems

## Please verify that you have completed the following steps

- [ ] I have self-reviewed my code.
- [ ] I have included test cases validating introduced feature/fix.
- [ ] I have updated documentation.

2023-10-11 16:08 UTC, AthenaCaesura requested changes

2023-10-11 16:08 UTC, AthenaCaesura commented on examples/ex_11_utility_scale.py
> +        lattice_type, save_base_path=cwd + "/new_results/"
Perhaps it should be in the existing "data" folder.

2023-10-12 09:07 UTC, SebastianMorawiec commented on examples/ex_11_utility_scale.py
> +        hardware_failure_tolerance=algorithm_implementation.error_budget.hardware_failure_tolerance,
I.... Don't know - I see it normally in both local version and on Github 😲 This is how style-fix formats it as well.

2023-10-12 09:08 UTC, SebastianMorawiec commented on examples/ex_11_utility_scale.py
> +        lattice_type, save_base_path=cwd + "/new_results/"
Now when Im thinking about it - we should allow users to set the path for the results IMHO. Ill make a new parameter for it

2023-10-16 20:07 UTC, AthenaCaesura approved these changes

2023-10-16 20:07 UTC, AthenaCaesura commented on examples/ex_11_utility_scale.py
> +        hardware_failure_tolerance=algorithm_implementation.error_budget.hardware_failure_tolerance,
It's strange that this isn't causing any errors.... But I guess it's probably ok. so long as the indentation works and looks ok.

2023-10-17 10:03 UTC, merged