Ac/dta2 350 small footprint factories
zapatacomputing/benchq pull request #152
Opened 2024-04-18 18:03 UTC by AthenaCaesura

## Description

Adds factories with small numbers of qubits. Factories were generated from [my fork of Daniel Litinski's magicstates software](https://github.com/AthenaCaesura/magicstates) in the small_footprint.py file of the best_factories folder.

## Please verify that you have completed the following steps

- [x] I have self-reviewed my code.
- [x] I have included test cases validating introduced feature/fix.
- [ ] I have updated documentation.

2024-04-19 17:48 UTC, max-radin requested changes
I feel like it would be cleaner to add these to iter_litinski_factories instead of creating a separate iterator. What do you think? Are there reasons to keep them separate?

2024-04-22 14:39 UTC, AthenaCaesura commented
These factories should be separate from the Litinski factories which are already in Benchq. This is because the current factories minimize spacetime volume where these factories only minimize space.

They have different uses, so users should be able to choose between them.

2024-04-24 03:10 UTC, max-radin commented
One small request: could you add docstrings that say that the one iterator is optimized for spacetime volume and the other for space? Otherwise looks good!

2024-05-07 13:22 UTC, max-radin approved these changes

2024-05-07 13:22 UTC, merged