Benchmarks for get_qsp_time_evolution_program
zapatacomputing/benchq pull request #38
Opened 2023-04-14 14:30 UTC by dexter2206

## Description

This adds simple benchmarks for `get_qsp_time_evolution_program` (prevoiusly `get_qsp_program`). Benchmarks might take a while to run, and hence I've decided to place them in separate directory so that noone runs them unintentionally when running the unitt ests.

Additionally, several test cases are exceptionally long. Those are run iff the environmental variable `SLOW_BENCHMARKS` is set (to any value). So, to run "fast" benchmarks:

```bash
pytest benchmarks/
```

and to run all benchmarks, including the slow ones:

```bash
SLOW_BENCHMARKS=1 pytest benchmarks/
```

The tests are implemented using the `pytest-benchmark` library, with the default settings (the number of iterations and repetitions are determined by `pytest-benchmark`).

## Please verify that you have completed the following steps

- [x] I have self-reviewed my code.
- [x] I have included test cases validating introduced feature/fix.
- [x] I have updated documentation.

2023-04-14 16:55 UTC, AthenaCaesura approved these changes

2023-04-14 16:55 UTC, AthenaCaesura commented on benchmarks/test_get_qsp_time_evolution_program.py
> +SKIP_SLOW = pytest.mark.skipif(
Good solution here!

2023-04-14 16:57 UTC, AthenaCaesura commented
I've approved this PR because it would work by itself. But can I ask you to add the tests that I have written up for the other parts of benchq?

2023-04-14 17:02 UTC, mstechly requested changes
Please add information how to use those tests to Readme.

2023-04-17 12:07 UTC, dexter2206 commented
> I've approved this PR because it would work by itself. But can I ask you to add the tests that I have written up for the other parts of benchq?

Don in [3dd8a15](https://github.com/zapatacomputing/benchq/pull/38/commits/3dd8a15e9b4f15117a31466928f6661add88697e)

2023-04-17 12:08 UTC, dexter2206 commented
> 533e6d4

README updated in [533e6d4](https://github.com/zapatacomputing/benchq/pull/38/commits/533e6d4d976c3a10c19ddbd5e8ed27e08ed656bf)

2023-04-17 12:10 UTC, dexter2206 commented on src/benchq/problem_ingestion/hamiltonian_generation.py
> +        data = json.load(f)
I'd like to keep this PR only about performance tests and not performance improvements. However, I'm certainly not opposed to introducing rapidjson if we find out that reading JSON file is one of the bottlenecks.

2023-04-17 12:25 UTC, mstechly approved these changes

2023-04-17 12:58 UTC, merged