Added the script for generating QAOA circuits for QUBO instances
zapatacomputing/benchq pull request #43
Opened 2023-04-18 17:08 UTC by Guoming-Wang

## Description

Include description of feature this PR introduces or a bug that it fixes. Include the following information:

- Context: why is it needed? In case of bug, what was the cause for the bug?
- Concise description of the implemented solution.
- If any dependencies are added, list them and justify why they are needed.

## Please verify that you have completed the following steps

- [ ] I have self-reviewed my code.
- [ ] I have included test cases validating introduced feature/fix.
- [ ] I have updated documentation.

2023-05-05 18:07 UTC, max-radin requested changes
Left a few minor comments.

2023-05-05 18:07 UTC, max-radin commented on src/benchq/algorithms/_qaoa.py
It looks like the QAOA functions aren't part of the public API right now. We could rename `_qaoa.py` to `qaoa.py`, or import the QAOA functions in `__init__.py`.

2023-05-05 19:16 UTC, AthenaCaesura commented on src/benchq/algorithms/_qaoa.py
I was really just following the convention that other algorithms had at the time. Seems like this format was outdated. I'll rename it to just `qaoa.py`.

2023-05-05 19:16 UTC, AthenaCaesura commented on src/benchq/algorithms/_qaoa.py
I was really just following the convention that other algorithms had at the time. Seems like this format was outdated. I'll rename it to just `qaoa.py`.

2023-05-05 19:16 UTC, AthenaCaesura commented on src/benchq/problem_ingestion/hamltonian_from_file.py
Done!

2023-05-05 19:17 UTC, AthenaCaesura commented on tests/benchq/algorithms/test_qaoa.py
> +def test_get_qaoa_circuit_produces_correct_output_for_meduim_coefficeints():
done!

2023-05-05 19:17 UTC, AthenaCaesura commented on src/benchq/algorithms/_qaoa.py
> +    qaoa = QAOA.default(cost_hamiltonian=hamiltonian, n_layers=1)
Good catch! Would have confused a lot of people later on. :sw

2023-05-05 19:38 UTC, AthenaCaesura commented on src/benchq/problem_ingestion/hamltonian_from_file.py
> +def _guoming_qaoa_hamiltonian_from_hdf5(data: h5py.File) -> PauliSum:
Done.

2023-05-05 19:38 UTC, AthenaCaesura commented on src/benchq/problem_ingestion/hamltonian_from_file.py
> +def _alex_molecule_hamiltonian_from_hdf5(data: h5py.File) -> PauliSum:
Done.

2023-05-09 04:50 UTC, max-radin approved these changes

2023-05-09 15:54 UTC, merged