Clean up ResourceInfo class
zapatacomputing/benchq pull request #69
Opened 2023-05-15 12:06 UTC by dexter2206

> **Warning**
> DON'T MERGE THIS PR UNTIL SCRIPTS ARE UPATED**
## Description

This PR unifies all classes storing resource info into a single generic class. The attributes common to all (or at least most) resource info classes were preserved in `ResourceInfo`, and the differing attributes were pushed to a separate `extra` field. Type of the `extra` field is the generic parameter of `ResourceInfo`.

For instance, for `AzureResourceInfo`, there exists a `AzureExtra` class storing things like raw data, and `AzureResourceInfo` is just equal to `ResourceInfo[AzureExtra]`.

The PR also fixes Azure tests and applies several minor style improvements.

## Please verify that you have completed the following steps

- [x] I have self-reviewed my code.
- [x] I have included test cases validating introduced feature/fix.
- [x] I have updated documentation.

2023-05-15 15:40 UTC, AthenaCaesura commented
This PR looks good! There's just one thing that bugs me here. Why not just use an inheritance structure for the `ResourceEstimates`? Then you can expose parameters directly and not have to write `.extra` everywhere.

2023-05-15 17:23 UTC, AthenaCaesura requested changes

2023-05-15 22:48 UTC, dexter2206 commented on src/benchq/data_structures/resource_info.py
What follows assumes that splitting between extra and non-extra parts of `ResourceInfo`  is what we want to have. 

The `max_graph_degree` field is stored in `extra` if `extra` is of `GraphData` type, while `n_logical_qubits` is a mandatory field. Hence:
- we cannot couple `max_graph_degree` to `n_logical_qubits` because not all resource estimates have `max_graph_degree`
- we cannot add additional logic to `GraphResourceInfo` because it is just a variant of `ResourceInfo` (`GraphResourceInfo is like `List[int]` to `list`, the former only adding type annotation describing a list for a purpose of static type analysis).

I think we should leave it as it is, and I also think it is correct conceptually. The `extra` field stores supplemental data specific to given estimation algorithm, compilation method etc., while other top-level fields describe mandatory information. For resources estimated with graph compilation it just so happens that one of this extra values is the same as one of the mandatory ones.

Does that make sense?

2023-05-15 23:27 UTC, dexter2206 commented
> This PR looks good! There's just one thing that bugs me here. Why not just use an inheritance structure for the `ResourceEstimates`? Then you can expose parameters directly and not have to write `.extra` everywhere.

There are two reasons why I didn't use inheritance to expose parameters directly.

The most important one: this is what the DTA2-127 is about - splitting resource info so that we have a clear distinction between estimated resources and extra information specific to the estimation and/or compilation method. I deviated from the original description in that I didn't place the resources part in a separate `resources` field, but I felt like it would make the whole data structure more cumbersome to use.

The second reason is that generally composition tends to lead to a looser coupling and cleaner architectures.

2023-05-17 15:53 UTC, AthenaCaesura approved these changes

2023-05-18 10:50 UTC, merged